/*
 * Jovan Gradojevic
 * 28/1/2020
 * Start of the rock, paper, scissors game that explains the rules then prompts the user to start.
 */

/**
 *
 * @author jogra6669
 */
public class rPs extends javax.swing.JFrame { 
    /**
     * Creates new form rPs
     */
    public rPs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleRps = new javax.swing.JLabel();
        Continue = new javax.swing.JToggleButton();
        instructionRps1 = new javax.swing.JLabel();
        instructionRps2 = new javax.swing.JLabel();
        instructionRps3 = new javax.swing.JLabel();
        instructionRps4 = new javax.swing.JLabel();
        instructionRps5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleRps.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 18)); // NOI18N
        titleRps.setText("Welcome to the rock, paper, scissors program!");

        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        instructionRps1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        instructionRps1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionRps1.setText("beat a computer at rock, paper, scissors. Remember, paper beats rock, rock");

        instructionRps2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        instructionRps2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionRps2.setText("The game is simple, choose one of the three options and see if you can");

        instructionRps3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        instructionRps3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionRps3.setText("beats scissors and scissors beats paper. Type in the number for which");

        instructionRps4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        instructionRps4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionRps4.setText("option you pick. Click results if you want to see the win and loss");

        instructionRps5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        instructionRps5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionRps5.setText("percentage. I hope you have fun!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instructionRps3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionRps4, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionRps5, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(titleRps)
                        .addGap(86, 86, 86)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructionRps1)
                    .addComponent(instructionRps2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(Continue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(titleRps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionRps2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionRps1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionRps3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionRps4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionRps5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Continue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
    this.setVisible(false);
    new rPsgame().setVisible(true); //Allows user to start the game by pressing the continue button
    }//GEN-LAST:event_ContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rPs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Continue;
    private javax.swing.JLabel instructionRps1;
    private javax.swing.JLabel instructionRps2;
    private javax.swing.JLabel instructionRps3;
    private javax.swing.JLabel instructionRps4;
    private javax.swing.JLabel instructionRps5;
    private javax.swing.JLabel titleRps;
    // End of variables declaration//GEN-END:variables
}
