/*
 * Jovan Gradojevic
 * 28/1/2020
 * Outputs the statistics of the rock, paper, scissors match then displays a final sentence.
 */

/**
 *
 * @author jogra6669
 */
public final class rPsresults extends javax.swing.JFrame {
    /**
     * This method grabs the wins and loses then displays out of 3
     */
    public void settingScores(){
        scorerPs.setText(rPsgame.userWins + "/3");
        loserPs.setText(rPsgame.computerWins + "/3");
    }
    
    /**
     * This method checks the wins and loses then outputs a sentence based on it
     */
    public void sentenceEnd(){
        if(rPsgame.userWins == rPsgame.computerWins){
           finalsentencerPs.setText("Not bad.");
        } else if(rPsgame.userWins > rPsgame.computerWins){
           finalsentencerPs.setText("You make me proud.");
        } else if(rPsgame.userWins < rPsgame.computerWins)
           finalsentencerPs.setText("You can do better than that."); 
    }
    /**
     * Creates new form rPsresults
     */
    public rPsresults() {
        initComponents();
        settingScores(); //Calls method when program is started
        sentenceEnd(); //Calls method when program is started
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleRps = new javax.swing.JLabel();
        winnerrPs = new javax.swing.JLabel();
        loserPs = new javax.swing.JLabel();
        sentencerPs = new javax.swing.JLabel();
        returnrPs = new javax.swing.JButton();
        scorerPs = new javax.swing.JLabel();
        loserrPs = new javax.swing.JLabel();
        finalsentencerPs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleRps.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 48)); // NOI18N
        titleRps.setText("Results");

        winnerrPs.setFont(new java.awt.Font("Myriad Web Pro", 0, 18)); // NOI18N
        winnerrPs.setText("You won!:");

        loserPs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        sentencerPs.setFont(new java.awt.Font("Myriad Web Pro", 0, 18)); // NOI18N
        sentencerPs.setText("Final sentence:");

        returnrPs.setText("Return");
        returnrPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnrPsActionPerformed(evt);
            }
        });

        scorerPs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        loserrPs.setFont(new java.awt.Font("Myriad Web Pro", 0, 18)); // NOI18N
        loserrPs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loserrPs.setText("You lost!:");

        finalsentencerPs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalsentencerPs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalsentencerPs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(titleRps))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loserrPs, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scorerPs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(winnerrPs, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(loserPs, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(sentencerPs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(returnrPs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleRps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(winnerrPs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scorerPs)
                .addGap(27, 27, 27)
                .addComponent(loserrPs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loserPs)
                .addGap(28, 28, 28)
                .addComponent(sentencerPs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalsentencerPs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(returnrPs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnrPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnrPsActionPerformed
        this.setVisible(false);
        new rPsgame().setVisible(true); //Allows user to return to the game screen
    }//GEN-LAST:event_returnrPsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rPsresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rPsresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rPsresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rPsresults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rPsresults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalsentencerPs;
    private javax.swing.JLabel loserPs;
    private javax.swing.JLabel loserrPs;
    private javax.swing.JButton returnrPs;
    private javax.swing.JLabel scorerPs;
    private javax.swing.JLabel sentencerPs;
    private javax.swing.JLabel titleRps;
    private javax.swing.JLabel winnerrPs;
    // End of variables declaration//GEN-END:variables
}
